# This file was *autogenerated* from the file arnborg_lazard.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
def eval(x1, x2, x3):
        return [x1**_sage_const_2 *x2*x3 + x1*x2**_sage_const_2 *x3 + x1*x2*x3**_sage_const_2  + x1*x2*x3 + x1*x2 + x1*x3 + x2*x3, x1**_sage_const_2 *x2**_sage_const_2 *x3 + x1*x2**_sage_const_2 *x3**_sage_const_2  + x1*x2*x3**_sage_const_2  + x1*x2*x3 + x1*x2 + x1 + x3, x1**_sage_const_2 *x2**_sage_const_2 *x3**_sage_const_2  + x1*x2**_sage_const_2 *x3**_sage_const_2  + x1*x2**_sage_const_2 *x3 + x1*x2*x3 + x1*x3 + x1 + _sage_const_1 ]

